---
- hosts: all
  

  
  tasks:

  - name: Slurp hosts file
    slurp:
      src: /home/jelle/rsync-backup-j-2024-10-08.log
    register: slurpfile

  - debug: msg="{{ slurpfile['content'] | b64decode }}"


