---
- hosts: all
  become: false
  gather_facts: false

  tasks:

  - name: Extract PS output.
    shell: 
      cmd: "ps -ef | grep pmon"
    register: pmon

  - name: Display PS output.
    debug:
      msg: "{{ pmon.stdout_lines }}"
