- name: checking service status
  hosts: ubuntu
  tasks:
  - name: checking service status
    command: systemctl status "{{ item }}"
    with_items:
    - nextcloud
    register: result
    ignore_errors: no
  - name: showing report
    debug:
     var: result
