---
- hosts: all
  

  
  tasks:
    

  
  - name: PreTest for freespace
    vars: 
      deprecation_warnings: False
      #mountname: '/opt/oracle'
      mount: "{{ ansible_mounts | selectattr('mount','equalto', mountname) | first }}"
  
    assert:
      that: mount.size_available > {{diskfree_req}}
      msg: 
      - "DANGER : disk space is low"
      - "'{{mountname}} only has {{mount.size_available}} available. Please correct"
    register: disk_free
