---
- hosts: all  
  become: true
  tasks:
  - name: Slurp the rsync backup log
    slurp:
      src: /root/rsynclogs/rsync-backup-f-$(date +"%Y-%m-%d").log
    register: slurpfile

  - debug: msg="{{ slurpfile['content'] | b64decode }}"


