---
- hosts: backupserver  
  become: true
  tasks:
  - name: Slurp the rsync backup log
    slurp:
      src: /root/rsynclogs/rsync.log
    register: slurpfile

  - debug: msg="{{ slurpfile['content'] | b64decode }}"


