- name: Read yaml file from the remote hosts
  hosts: all
  tasks:
    - name: Read yaml file from host
      ansible.builtin.command: cat /home/jelle/rsynclogs/rsync-backup-j-$(date +"%Y-%m-%d").log
      register: command_result

    - name: Print result
      ansible.builtin.debug:
        var: command_result

    - name: Load data into variable
      ansible.builtin.set_fact:
        my_var: "{{ command_result.stdout }}"

    - name: Print raw string
      ansible.builtin.debug:
        var: my_var.key0
